### ISSUE TITLE
Checklist Server

### ISSUE THREAD

**Issue by dot-william** [simonqq21/CSNETWK-Message-Board-MP#1]
### **_{"command":"ret_code", "code_no":201} Command parameters incomplete}_**
- [x] Incomplete if there is value in the username for register
- [x] Incomplete if there is value in the username for deregister
- [x] Incomplete if there is value in the username for message
- [x] Incomplete if there is no value in the message
- [x] Incomplete if there is no value in the command (is this possible?)

### _**{"command":"ret_code", "code_no":301} Command unknown**_
- [x] Command unknown if command is netiher: register, deregister, msg

### **_{"command":"ret_code", "code_no":401} Command accepted_**

_If register is valid_
- [x] Register is valid if the username is unique and does not exist already
- [x] Register is *invalid* if the username already exists and is not unique _(in this case return user already exists)_

_If deregisteration is successful_ 
- [x] Deregistration is successful if the username is in the list of users
- [x] Deregistration is *unsuccessful* if the username is NOT in the list of users _(in this case return user not registered)_

_If sending message is successful_ 
- [x] Message is successful if the user exists and if the message is not empty
- [x] Message is *unsuccessful* if there is no value _(in this case, return incomplete parameters)_
- [x] If the user DOES NOT EXIST and message is not empty _(in this case, return user not registered)_
- [x] If the user does not exist and message is empty 
- [x] If the user exists but the message is empty 

### **_{"command":"ret_code", "code_no":501} User not registered_**
- [x] User not registered returned if username does not exist in the list

### **_{"command":"ret_code", "code_no":502} User account exists_**
- [x] User account exists if user is trying to create an account but the account already exists
